const assetModules = import.meta.glob("../assets/extracted/**/*.png", { eager: true, import: "default" }) as Record<string, string>;

export type ElementFamily = "florale" | "feuillage" | "marin" | "atmosphere";

export type ElementAsset = { id: string; label: string; family: ElementFamily; width: number; height: number; src: string; source: string; };

const manifest = [
  { id: 'florale-01-01', label: 'Florale 1', family: 'florale', width: 276, height: 307, srcKey: '../assets/extracted/florale/florale-01-01.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-02', label: 'Florale 2', family: 'florale', width: 222, height: 340, srcKey: '../assets/extracted/florale/florale-01-02.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-03', label: 'Florale 3', family: 'florale', width: 168, height: 289, srcKey: '../assets/extracted/florale/florale-01-03.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-04', label: 'Florale 4', family: 'florale', width: 240, height: 320, srcKey: '../assets/extracted/florale/florale-01-04.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-05', label: 'Florale 5', family: 'florale', width: 205, height: 254, srcKey: '../assets/extracted/florale/florale-01-05.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-06', label: 'Florale 6', family: 'florale', width: 192, height: 321, srcKey: '../assets/extracted/florale/florale-01-06.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-07', label: 'Florale 7', family: 'florale', width: 115, height: 128, srcKey: '../assets/extracted/florale/florale-01-07.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-08', label: 'Florale 8', family: 'florale', width: 207, height: 311, srcKey: '../assets/extracted/florale/florale-01-08.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-09', label: 'Florale 9', family: 'florale', width: 201, height: 317, srcKey: '../assets/extracted/florale/florale-01-09.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-10', label: 'Florale 10', family: 'florale', width: 204, height: 275, srcKey: '../assets/extracted/florale/florale-01-10.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-11', label: 'Florale 11', family: 'florale', width: 185, height: 280, srcKey: '../assets/extracted/florale/florale-01-11.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-12', label: 'Florale 12', family: 'florale', width: 220, height: 251, srcKey: '../assets/extracted/florale/florale-01-12.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-13', label: 'Florale 13', family: 'florale', width: 245, height: 228, srcKey: '../assets/extracted/florale/florale-01-13.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-14', label: 'Florale 14', family: 'florale', width: 161, height: 315, srcKey: '../assets/extracted/florale/florale-01-14.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-15', label: 'Florale 15', family: 'florale', width: 221, height: 363, srcKey: '../assets/extracted/florale/florale-01-15.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-16', label: 'Florale 16', family: 'florale', width: 334, height: 310, srcKey: '../assets/extracted/florale/florale-01-16.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-17', label: 'Florale 17', family: 'florale', width: 210, height: 376, srcKey: '../assets/extracted/florale/florale-01-17.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-18', label: 'Florale 18', family: 'florale', width: 217, height: 335, srcKey: '../assets/extracted/florale/florale-01-18.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-19', label: 'Florale 19', family: 'florale', width: 201, height: 378, srcKey: '../assets/extracted/florale/florale-01-19.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-20', label: 'Florale 20', family: 'florale', width: 116, height: 73, srcKey: '../assets/extracted/florale/florale-01-20.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-21', label: 'Florale 21', family: 'florale', width: 99, height: 79, srcKey: '../assets/extracted/florale/florale-01-21.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-22', label: 'Florale 22', family: 'florale', width: 114, height: 77, srcKey: '../assets/extracted/florale/florale-01-22.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-23', label: 'Florale 23', family: 'florale', width: 108, height: 79, srcKey: '../assets/extracted/florale/florale-01-23.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-24', label: 'Florale 24', family: 'florale', width: 83, height: 68, srcKey: '../assets/extracted/florale/florale-01-24.png', source: 'source-fleurs-01.png' },
  { id: 'marin-02-01', label: 'Marin 1', family: 'marin', width: 181, height: 255, srcKey: '../assets/extracted/marin/marin-02-01.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-02', label: 'Marin 2', family: 'marin', width: 150, height: 282, srcKey: '../assets/extracted/marin/marin-02-02.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-03', label: 'Marin 3', family: 'marin', width: 261, height: 255, srcKey: '../assets/extracted/marin/marin-02-03.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-04', label: 'Marin 4', family: 'marin', width: 239, height: 236, srcKey: '../assets/extracted/marin/marin-02-04.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-05', label: 'Marin 5', family: 'marin', width: 200, height: 243, srcKey: '../assets/extracted/marin/marin-02-05.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-06', label: 'Marin 6', family: 'marin', width: 186, height: 198, srcKey: '../assets/extracted/marin/marin-02-06.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-07', label: 'Marin 7', family: 'marin', width: 187, height: 391, srcKey: '../assets/extracted/marin/marin-02-07.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-08', label: 'Marin 8', family: 'marin', width: 243, height: 242, srcKey: '../assets/extracted/marin/marin-02-08.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-09', label: 'Marin 9', family: 'marin', width: 244, height: 238, srcKey: '../assets/extracted/marin/marin-02-09.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-10', label: 'Marin 10', family: 'marin', width: 217, height: 221, srcKey: '../assets/extracted/marin/marin-02-10.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-11', label: 'Marin 11', family: 'marin', width: 210, height: 187, srcKey: '../assets/extracted/marin/marin-02-11.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-12', label: 'Marin 12', family: 'marin', width: 198, height: 178, srcKey: '../assets/extracted/marin/marin-02-12.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-13', label: 'Marin 13', family: 'marin', width: 134, height: 285, srcKey: '../assets/extracted/marin/marin-02-13.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-14', label: 'Marin 14', family: 'marin', width: 215, height: 299, srcKey: '../assets/extracted/marin/marin-02-14.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-15', label: 'Marin 15', family: 'marin', width: 282, height: 208, srcKey: '../assets/extracted/marin/marin-02-15.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-16', label: 'Marin 16', family: 'marin', width: 250, height: 209, srcKey: '../assets/extracted/marin/marin-02-16.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-17', label: 'Marin 17', family: 'marin', width: 135, height: 71, srcKey: '../assets/extracted/marin/marin-02-17.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-18', label: 'Marin 18', family: 'marin', width: 137, height: 81, srcKey: '../assets/extracted/marin/marin-02-18.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-19', label: 'Marin 19', family: 'marin', width: 127, height: 69, srcKey: '../assets/extracted/marin/marin-02-19.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-20', label: 'Marin 20', family: 'marin', width: 180, height: 298, srcKey: '../assets/extracted/marin/marin-02-20.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-21', label: 'Marin 21', family: 'marin', width: 121, height: 66, srcKey: '../assets/extracted/marin/marin-02-21.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-22', label: 'Marin 22', family: 'marin', width: 225, height: 233, srcKey: '../assets/extracted/marin/marin-02-22.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-23', label: 'Marin 23', family: 'marin', width: 194, height: 191, srcKey: '../assets/extracted/marin/marin-02-23.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-24', label: 'Marin 24', family: 'marin', width: 224, height: 183, srcKey: '../assets/extracted/marin/marin-02-24.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-25', label: 'Marin 25', family: 'marin', width: 146, height: 176, srcKey: '../assets/extracted/marin/marin-02-25.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-26', label: 'Marin 26', family: 'marin', width: 334, height: 120, srcKey: '../assets/extracted/marin/marin-02-26.png', source: 'source-marin-organique.png' },
  { id: 'atmosphere-03-01', label: 'Atmosphere 1', family: 'atmosphere', width: 1207, height: 1178, srcKey: '../assets/extracted/atmosphere/atmosphere-03-01.png', source: 'source-atmosphere-02.png' },
  { id: 'feuillage-04-01', label: 'Feuillage 1', family: 'feuillage', width: 46, height: 134, srcKey: '../assets/extracted/feuillage/feuillage-04-01.png', source: 'source-herbe-01.png' },
  { id: 'feuillage-04-02', label: 'Feuillage 2', family: 'feuillage', width: 97, height: 642, srcKey: '../assets/extracted/feuillage/feuillage-04-02.png', source: 'source-herbe-01.png' },
  { id: 'feuillage-04-03', label: 'Feuillage 3', family: 'feuillage', width: 55, height: 210, srcKey: '../assets/extracted/feuillage/feuillage-04-03.png', source: 'source-herbe-01.png' },
  { id: 'feuillage-04-04', label: 'Feuillage 4', family: 'feuillage', width: 93, height: 173, srcKey: '../assets/extracted/feuillage/feuillage-04-04.png', source: 'source-herbe-01.png' },
  { id: 'feuillage-04-05', label: 'Feuillage 5', family: 'feuillage', width: 100, height: 608, srcKey: '../assets/extracted/feuillage/feuillage-04-05.png', source: 'source-herbe-01.png' },
  { id: 'feuillage-04-06', label: 'Feuillage 6', family: 'feuillage', width: 232, height: 579, srcKey: '../assets/extracted/feuillage/feuillage-04-06.png', source: 'source-herbe-01.png' },
  { id: 'feuillage-04-07', label: 'Feuillage 7', family: 'feuillage', width: 362, height: 571, srcKey: '../assets/extracted/feuillage/feuillage-04-07.png', source: 'source-herbe-01.png' },
  { id: 'feuillage-04-08', label: 'Feuillage 8', family: 'feuillage', width: 87, height: 168, srcKey: '../assets/extracted/feuillage/feuillage-04-08.png', source: 'source-herbe-01.png' },
  { id: 'feuillage-04-09', label: 'Feuillage 9', family: 'feuillage', width: 54, height: 171, srcKey: '../assets/extracted/feuillage/feuillage-04-09.png', source: 'source-herbe-01.png' },
  { id: 'feuillage-04-10', label: 'Feuillage 10', family: 'feuillage', width: 78, height: 114, srcKey: '../assets/extracted/feuillage/feuillage-04-10.png', source: 'source-herbe-01.png' },
  { id: 'feuillage-04-11', label: 'Feuillage 11', family: 'feuillage', width: 63, height: 191, srcKey: '../assets/extracted/feuillage/feuillage-04-11.png', source: 'source-herbe-01.png' },
  { id: 'feuillage-04-12', label: 'Feuillage 12', family: 'feuillage', width: 57, height: 190, srcKey: '../assets/extracted/feuillage/feuillage-04-12.png', source: 'source-herbe-01.png' },
  { id: 'feuillage-04-13', label: 'Feuillage 13', family: 'feuillage', width: 208, height: 632, srcKey: '../assets/extracted/feuillage/feuillage-04-13.png', source: 'source-herbe-01.png' },
  { id: 'feuillage-04-14', label: 'Feuillage 14', family: 'feuillage', width: 82, height: 145, srcKey: '../assets/extracted/feuillage/feuillage-04-14.png', source: 'source-herbe-01.png' },
  { id: 'feuillage-04-15', label: 'Feuillage 15', family: 'feuillage', width: 256, height: 606, srcKey: '../assets/extracted/feuillage/feuillage-04-15.png', source: 'source-herbe-01.png' },
  { id: 'feuillage-04-16', label: 'Feuillage 16', family: 'feuillage', width: 263, height: 554, srcKey: '../assets/extracted/feuillage/feuillage-04-16.png', source: 'source-herbe-01.png' },
  { id: 'feuillage-04-17', label: 'Feuillage 17', family: 'feuillage', width: 115, height: 138, srcKey: '../assets/extracted/feuillage/feuillage-04-17.png', source: 'source-herbe-01.png' },
  { id: 'feuillage-05-01', label: 'Feuillage 1', family: 'feuillage', width: 270, height: 627, srcKey: '../assets/extracted/feuillage/feuillage-05-01.png', source: 'source-herbe-02.png' },
  { id: 'feuillage-05-02', label: 'Feuillage 2', family: 'feuillage', width: 323, height: 603, srcKey: '../assets/extracted/feuillage/feuillage-05-02.png', source: 'source-herbe-02.png' },
  { id: 'feuillage-05-03', label: 'Feuillage 3', family: 'feuillage', width: 249, height: 641, srcKey: '../assets/extracted/feuillage/feuillage-05-03.png', source: 'source-herbe-02.png' },
  { id: 'feuillage-05-04', label: 'Feuillage 4', family: 'feuillage', width: 276, height: 637, srcKey: '../assets/extracted/feuillage/feuillage-05-04.png', source: 'source-herbe-02.png' },
  { id: 'feuillage-05-05', label: 'Feuillage 5', family: 'feuillage', width: 299, height: 536, srcKey: '../assets/extracted/feuillage/feuillage-05-05.png', source: 'source-herbe-02.png' },
  { id: 'feuillage-06-01', label: 'Feuillage 1', family: 'feuillage', width: 348, height: 521, srcKey: '../assets/extracted/feuillage/feuillage-06-01.png', source: 'source-herbe-03.png' },
  { id: 'feuillage-06-02', label: 'Feuillage 2', family: 'feuillage', width: 260, height: 448, srcKey: '../assets/extracted/feuillage/feuillage-06-02.png', source: 'source-herbe-03.png' },
  { id: 'feuillage-06-03', label: 'Feuillage 3', family: 'feuillage', width: 404, height: 261, srcKey: '../assets/extracted/feuillage/feuillage-06-03.png', source: 'source-herbe-03.png' },
  { id: 'feuillage-06-04', label: 'Feuillage 4', family: 'feuillage', width: 272, height: 493, srcKey: '../assets/extracted/feuillage/feuillage-06-04.png', source: 'source-herbe-03.png' },
  { id: 'feuillage-06-05', label: 'Feuillage 5', family: 'feuillage', width: 329, height: 489, srcKey: '../assets/extracted/feuillage/feuillage-06-05.png', source: 'source-herbe-03.png' },
  { id: 'feuillage-07-01', label: 'Feuillage 1', family: 'feuillage', width: 311, height: 640, srcKey: '../assets/extracted/feuillage/feuillage-07-01.png', source: 'source-herbe-05.png' },
  { id: 'feuillage-07-02', label: 'Feuillage 2', family: 'feuillage', width: 75, height: 187, srcKey: '../assets/extracted/feuillage/feuillage-07-02.png', source: 'source-herbe-05.png' },
  { id: 'feuillage-07-03', label: 'Feuillage 3', family: 'feuillage', width: 280, height: 548, srcKey: '../assets/extracted/feuillage/feuillage-07-03.png', source: 'source-herbe-05.png' },
  { id: 'feuillage-07-04', label: 'Feuillage 4', family: 'feuillage', width: 114, height: 221, srcKey: '../assets/extracted/feuillage/feuillage-07-04.png', source: 'source-herbe-05.png' },
  { id: 'feuillage-07-05', label: 'Feuillage 5', family: 'feuillage', width: 214, height: 182, srcKey: '../assets/extracted/feuillage/feuillage-07-05.png', source: 'source-herbe-05.png' },
  { id: 'feuillage-07-06', label: 'Feuillage 6', family: 'feuillage', width: 139, height: 129, srcKey: '../assets/extracted/feuillage/feuillage-07-06.png', source: 'source-herbe-05.png' },
  { id: 'feuillage-07-07', label: 'Feuillage 7', family: 'feuillage', width: 235, height: 218, srcKey: '../assets/extracted/feuillage/feuillage-07-07.png', source: 'source-herbe-05.png' },
  { id: 'feuillage-07-08', label: 'Feuillage 8', family: 'feuillage', width: 210, height: 157, srcKey: '../assets/extracted/feuillage/feuillage-07-08.png', source: 'source-herbe-05.png' },
  { id: 'feuillage-07-09', label: 'Feuillage 9', family: 'feuillage', width: 296, height: 175, srcKey: '../assets/extracted/feuillage/feuillage-07-09.png', source: 'source-herbe-05.png' },
  { id: 'feuillage-07-10', label: 'Feuillage 10', family: 'feuillage', width: 223, height: 584, srcKey: '../assets/extracted/feuillage/feuillage-07-10.png', source: 'source-herbe-05.png' },
  { id: 'feuillage-07-11', label: 'Feuillage 11', family: 'feuillage', width: 243, height: 542, srcKey: '../assets/extracted/feuillage/feuillage-07-11.png', source: 'source-herbe-05.png' },
  { id: 'feuillage-07-12', label: 'Feuillage 12', family: 'feuillage', width: 371, height: 269, srcKey: '../assets/extracted/feuillage/feuillage-07-12.png', source: 'source-herbe-05.png' },
  { id: 'feuillage-08-01', label: 'Feuillage 1', family: 'feuillage', width: 288, height: 704, srcKey: '../assets/extracted/feuillage/feuillage-08-01.png', source: 'source-herbe-06.png' },
  { id: 'feuillage-08-02', label: 'Feuillage 2', family: 'feuillage', width: 275, height: 650, srcKey: '../assets/extracted/feuillage/feuillage-08-02.png', source: 'source-herbe-06.png' },
  { id: 'feuillage-08-03', label: 'Feuillage 3', family: 'feuillage', width: 80, height: 90, srcKey: '../assets/extracted/feuillage/feuillage-08-03.png', source: 'source-herbe-06.png' },
  { id: 'feuillage-08-04', label: 'Feuillage 4', family: 'feuillage', width: 353, height: 529, srcKey: '../assets/extracted/feuillage/feuillage-08-04.png', source: 'source-herbe-06.png' },
  { id: 'feuillage-09-01', label: 'Feuillage 1', family: 'feuillage', width: 351, height: 547, srcKey: '../assets/extracted/feuillage/feuillage-09-01.png', source: 'source-herbe-07.png' },
  { id: 'feuillage-09-02', label: 'Feuillage 2', family: 'feuillage', width: 325, height: 560, srcKey: '../assets/extracted/feuillage/feuillage-09-02.png', source: 'source-herbe-07.png' },
  { id: 'feuillage-09-03', label: 'Feuillage 3', family: 'feuillage', width: 309, height: 353, srcKey: '../assets/extracted/feuillage/feuillage-09-03.png', source: 'source-herbe-07.png' },
  { id: 'feuillage-09-04', label: 'Feuillage 4', family: 'feuillage', width: 356, height: 515, srcKey: '../assets/extracted/feuillage/feuillage-09-04.png', source: 'source-herbe-07.png' },
  { id: 'feuillage-09-05', label: 'Feuillage 5', family: 'feuillage', width: 326, height: 485, srcKey: '../assets/extracted/feuillage/feuillage-09-05.png', source: 'source-herbe-07.png' },
  { id: 'feuillage-09-06', label: 'Feuillage 6', family: 'feuillage', width: 310, height: 360, srcKey: '../assets/extracted/feuillage/feuillage-09-06.png', source: 'source-herbe-07.png' },
] as const;

export const ELEMENTS: ElementAsset[] = manifest.map((item) => ({
  id: item.id, label: item.label, family: item.family, width: item.width, height: item.height, src: assetModules[item.srcKey], source: item.source,
}));

export const ELEMENT_FAMILIES: { id: ElementFamily; label: string }[] = [
  { id: "florale", label: "Fleurs" },
  { id: "feuillage", label: "Feuillages" },
  { id: "marin", label: "Marin" },
  { id: "atmosphere", label: "Atmosphères" },
];

export function getElementById(id: string) { return ELEMENTS.find((item) => item.id === id); }