const assetModules = import.meta.glob("../assets/extracted/**/*.png", { eager: true, import: "default" }) as Record<string, string>;

export type ElementFamily = "florale" | "feuillage" | "marin" | "atmosphere" | "couronne" | "fleur";

export type ElementAsset = { id: string; label: string; family: ElementFamily; width: number; height: number; src: string; source: string; };

const manifest = [
  { id: 'florale-01-01', label: 'Florale 1', family: 'florale', width: 276, height: 307, srcKey: '../assets/extracted/florale/florale-01-01.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-02', label: 'Florale 2', family: 'florale', width: 222, height: 340, srcKey: '../assets/extracted/florale/florale-01-02.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-03', label: 'Florale 3', family: 'florale', width: 168, height: 289, srcKey: '../assets/extracted/florale/florale-01-03.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-04', label: 'Florale 4', family: 'florale', width: 240, height: 320, srcKey: '../assets/extracted/florale/florale-01-04.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-05', label: 'Florale 5', family: 'florale', width: 205, height: 254, srcKey: '../assets/extracted/florale/florale-01-05.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-06', label: 'Florale 6', family: 'florale', width: 192, height: 321, srcKey: '../assets/extracted/florale/florale-01-06.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-07', label: 'Florale 7', family: 'florale', width: 115, height: 128, srcKey: '../assets/extracted/florale/florale-01-07.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-08', label: 'Florale 8', family: 'florale', width: 207, height: 311, srcKey: '../assets/extracted/florale/florale-01-08.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-09', label: 'Florale 9', family: 'florale', width: 201, height: 317, srcKey: '../assets/extracted/florale/florale-01-09.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-10', label: 'Florale 10', family: 'florale', width: 204, height: 275, srcKey: '../assets/extracted/florale/florale-01-10.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-11', label: 'Florale 11', family: 'florale', width: 185, height: 280, srcKey: '../assets/extracted/florale/florale-01-11.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-12', label: 'Florale 12', family: 'florale', width: 220, height: 251, srcKey: '../assets/extracted/florale/florale-01-12.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-13', label: 'Florale 13', family: 'florale', width: 245, height: 228, srcKey: '../assets/extracted/florale/florale-01-13.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-14', label: 'Florale 14', family: 'florale', width: 161, height: 315, srcKey: '../assets/extracted/florale/florale-01-14.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-15', label: 'Florale 15', family: 'florale', width: 221, height: 363, srcKey: '../assets/extracted/florale/florale-01-15.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-16', label: 'Florale 16', family: 'florale', width: 334, height: 310, srcKey: '../assets/extracted/florale/florale-01-16.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-17', label: 'Florale 17', family: 'florale', width: 210, height: 376, srcKey: '../assets/extracted/florale/florale-01-17.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-18', label: 'Florale 18', family: 'florale', width: 217, height: 335, srcKey: '../assets/extracted/florale/florale-01-18.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-19', label: 'Florale 19', family: 'florale', width: 201, height: 378, srcKey: '../assets/extracted/florale/florale-01-19.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-20', label: 'Florale 20', family: 'florale', width: 116, height: 73, srcKey: '../assets/extracted/florale/florale-01-20.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-21', label: 'Florale 21', family: 'florale', width: 99, height: 79, srcKey: '../assets/extracted/florale/florale-01-21.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-22', label: 'Florale 22', family: 'florale', width: 114, height: 77, srcKey: '../assets/extracted/florale/florale-01-22.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-23', label: 'Florale 23', family: 'florale', width: 108, height: 79, srcKey: '../assets/extracted/florale/florale-01-23.png', source: 'source-fleurs-01.png' },
  { id: 'florale-01-24', label: 'Florale 24', family: 'florale', width: 83, height: 68, srcKey: '../assets/extracted/florale/florale-01-24.png', source: 'source-fleurs-01.png' },
  { id: 'marin-02-01', label: 'Marin 1', family: 'marin', width: 181, height: 255, srcKey: '../assets/extracted/marin/marin-02-01.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-02', label: 'Marin 2', family: 'marin', width: 150, height: 282, srcKey: '../assets/extracted/marin/marin-02-02.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-03', label: 'Marin 3', family: 'marin', width: 261, height: 255, srcKey: '../assets/extracted/marin/marin-02-03.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-04', label: 'Marin 4', family: 'marin', width: 239, height: 236, srcKey: '../assets/extracted/marin/marin-02-04.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-05', label: 'Marin 5', family: 'marin', width: 200, height: 243, srcKey: '../assets/extracted/marin/marin-02-05.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-06', label: 'Marin 6', family: 'marin', width: 186, height: 198, srcKey: '../assets/extracted/marin/marin-02-06.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-07', label: 'Marin 7', family: 'marin', width: 187, height: 391, srcKey: '../assets/extracted/marin/marin-02-07.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-08', label: 'Marin 8', family: 'marin', width: 243, height: 242, srcKey: '../assets/extracted/marin/marin-02-08.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-09', label: 'Marin 9', family: 'marin', width: 244, height: 238, srcKey: '../assets/extracted/marin/marin-02-09.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-10', label: 'Marin 10', family: 'marin', width: 217, height: 221, srcKey: '../assets/extracted/marin/marin-02-10.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-11', label: 'Marin 11', family: 'marin', width: 210, height: 187, srcKey: '../assets/extracted/marin/marin-02-11.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-12', label: 'Marin 12', family: 'marin', width: 198, height: 178, srcKey: '../assets/extracted/marin/marin-02-12.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-13', label: 'Marin 13', family: 'marin', width: 134, height: 285, srcKey: '../assets/extracted/marin/marin-02-13.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-14', label: 'Marin 14', family: 'marin', width: 215, height: 299, srcKey: '../assets/extracted/marin/marin-02-14.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-15', label: 'Marin 15', family: 'marin', width: 282, height: 208, srcKey: '../assets/extracted/marin/marin-02-15.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-16', label: 'Marin 16', family: 'marin', width: 250, height: 209, srcKey: '../assets/extracted/marin/marin-02-16.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-17', label: 'Marin 17', family: 'marin', width: 135, height: 71, srcKey: '../assets/extracted/marin/marin-02-17.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-18', label: 'Marin 18', family: 'marin', width: 137, height: 81, srcKey: '../assets/extracted/marin/marin-02-18.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-19', label: 'Marin 19', family: 'marin', width: 127, height: 69, srcKey: '../assets/extracted/marin/marin-02-19.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-20', label: 'Marin 20', family: 'marin', width: 180, height: 298, srcKey: '../assets/extracted/marin/marin-02-20.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-21', label: 'Marin 21', family: 'marin', width: 121, height: 66, srcKey: '../assets/extracted/marin/marin-02-21.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-22', label: 'Marin 22', family: 'marin', width: 225, height: 233, srcKey: '../assets/extracted/marin/marin-02-22.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-23', label: 'Marin 23', family: 'marin', width: 194, height: 191, srcKey: '../assets/extracted/marin/marin-02-23.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-24', label: 'Marin 24', family: 'marin', width: 224, height: 183, srcKey: '../assets/extracted/marin/marin-02-24.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-25', label: 'Marin 25', family: 'marin', width: 146, height: 176, srcKey: '../assets/extracted/marin/marin-02-25.png', source: 'source-marin-organique.png' },
  { id: 'marin-02-26', label: 'Marin 26', family: 'marin', width: 334, height: 120, srcKey: '../assets/extracted/marin/marin-02-26.png', source: 'source-marin-organique.png' },
  { id: 'atmosphere-03-01', label: 'Atmosphere 1', family: 'atmosphere', width: 1207, height: 1178, srcKey: '../assets/extracted/atmosphere/atmosphere-03-01.png', source: 'source-atmosphere-02.png' },
  { id: 'feuillage-04-01', label: 'Feuillage 1', family: 'feuillage', width: 46, height: 134, srcKey: '../assets/extracted/feuillage/feuillage-04-01.png', source: 'source-herbe-01.png' },
  { id: 'feuillage-04-02', label: 'Feuillage 2', family: 'feuillage', width: 97, height: 642, srcKey: '../assets/extracted/feuillage/feuillage-04-02.png', source: 'source-herbe-01.png' },
  { id: 'feuillage-04-03', label: 'Feuillage 3', family: 'feuillage', width: 55, height: 210, srcKey: '../assets/extracted/feuillage/feuillage-04-03.png', source: 'source-herbe-01.png' },
  { id: 'feuillage-04-04', label: 'Feuillage 4', family: 'feuillage', width: 93, height: 173, srcKey: '../assets/extracted/feuillage/feuillage-04-04.png', source: 'source-herbe-01.png' },
  { id: 'feuillage-04-05', label: 'Feuillage 5', family: 'feuillage', width: 100, height: 608, srcKey: '../assets/extracted/feuillage/feuillage-04-05.png', source: 'source-herbe-01.png' },
  { id: 'feuillage-04-06', label: 'Feuillage 6', family: 'feuillage', width: 232, height: 579, srcKey: '../assets/extracted/feuillage/feuillage-04-06.png', source: 'source-herbe-01.png' },
  { id: 'feuillage-04-07', label: 'Feuillage 7', family: 'feuillage', width: 362, height: 571, srcKey: '../assets/extracted/feuillage/feuillage-04-07.png', source: 'source-herbe-01.png' },
  { id: 'feuillage-04-08', label: 'Feuillage 8', family: 'feuillage', width: 87, height: 168, srcKey: '../assets/extracted/feuillage/feuillage-04-08.png', source: 'source-herbe-01.png' },
  { id: 'feuillage-04-09', label: 'Feuillage 9', family: 'feuillage', width: 54, height: 171, srcKey: '../assets/extracted/feuillage/feuillage-04-09.png', source: 'source-herbe-01.png' },
  { id: 'feuillage-04-10', label: 'Feuillage 10', family: 'feuillage', width: 78, height: 114, srcKey: '../assets/extracted/feuillage/feuillage-04-10.png', source: 'source-herbe-01.png' },
  { id: 'feuillage-04-11', label: 'Feuillage 11', family: 'feuillage', width: 63, height: 191, srcKey: '../assets/extracted/feuillage/feuillage-04-11.png', source: 'source-herbe-01.png' },
  { id: 'feuillage-04-12', label: 'Feuillage 12', family: 'feuillage', width: 57, height: 190, srcKey: '../assets/extracted/feuillage/feuillage-04-12.png', source: 'source-herbe-01.png' },
  { id: 'feuillage-04-13', label: 'Feuillage 13', family: 'feuillage', width: 208, height: 632, srcKey: '../assets/extracted/feuillage/feuillage-04-13.png', source: 'source-herbe-01.png' },
  { id: 'feuillage-04-14', label: 'Feuillage 14', family: 'feuillage', width: 82, height: 145, srcKey: '../assets/extracted/feuillage/feuillage-04-14.png', source: 'source-herbe-01.png' },
  { id: 'feuillage-04-15', label: 'Feuillage 15', family: 'feuillage', width: 256, height: 606, srcKey: '../assets/extracted/feuillage/feuillage-04-15.png', source: 'source-herbe-01.png' },
  { id: 'feuillage-04-16', label: 'Feuillage 16', family: 'feuillage', width: 263, height: 554, srcKey: '../assets/extracted/feuillage/feuillage-04-16.png', source: 'source-herbe-01.png' },
  { id: 'feuillage-04-17', label: 'Feuillage 17', family: 'feuillage', width: 115, height: 138, srcKey: '../assets/extracted/feuillage/feuillage-04-17.png', source: 'source-herbe-01.png' },
  { id: 'feuillage-05-01', label: 'Feuillage 1', family: 'feuillage', width: 270, height: 627, srcKey: '../assets/extracted/feuillage/feuillage-05-01.png', source: 'source-herbe-02.png' },
  { id: 'feuillage-05-02', label: 'Feuillage 2', family: 'feuillage', width: 323, height: 603, srcKey: '../assets/extracted/feuillage/feuillage-05-02.png', source: 'source-herbe-02.png' },
  { id: 'feuillage-05-03', label: 'Feuillage 3', family: 'feuillage', width: 249, height: 641, srcKey: '../assets/extracted/feuillage/feuillage-05-03.png', source: 'source-herbe-02.png' },
  { id: 'feuillage-05-04', label: 'Feuillage 4', family: 'feuillage', width: 276, height: 637, srcKey: '../assets/extracted/feuillage/feuillage-05-04.png', source: 'source-herbe-02.png' },
  { id: 'feuillage-05-05', label: 'Feuillage 5', family: 'feuillage', width: 299, height: 536, srcKey: '../assets/extracted/feuillage/feuillage-05-05.png', source: 'source-herbe-02.png' },
  { id: 'feuillage-06-01', label: 'Feuillage 1', family: 'feuillage', width: 348, height: 521, srcKey: '../assets/extracted/feuillage/feuillage-06-01.png', source: 'source-herbe-03.png' },
  { id: 'feuillage-06-02', label: 'Feuillage 2', family: 'feuillage', width: 260, height: 448, srcKey: '../assets/extracted/feuillage/feuillage-06-02.png', source: 'source-herbe-03.png' },
  { id: 'feuillage-06-03', label: 'Feuillage 3', family: 'feuillage', width: 404, height: 261, srcKey: '../assets/extracted/feuillage/feuillage-06-03.png', source: 'source-herbe-03.png' },
  { id: 'feuillage-06-04', label: 'Feuillage 4', family: 'feuillage', width: 272, height: 493, srcKey: '../assets/extracted/feuillage/feuillage-06-04.png', source: 'source-herbe-03.png' },
  { id: 'feuillage-06-05', label: 'Feuillage 5', family: 'feuillage', width: 329, height: 489, srcKey: '../assets/extracted/feuillage/feuillage-06-05.png', source: 'source-herbe-03.png' },
  { id: 'feuillage-07-01', label: 'Feuillage 1', family: 'feuillage', width: 311, height: 640, srcKey: '../assets/extracted/feuillage/feuillage-07-01.png', source: 'source-herbe-05.png' },
  { id: 'feuillage-07-02', label: 'Feuillage 2', family: 'feuillage', width: 75, height: 187, srcKey: '../assets/extracted/feuillage/feuillage-07-02.png', source: 'source-herbe-05.png' },
  { id: 'feuillage-07-03', label: 'Feuillage 3', family: 'feuillage', width: 280, height: 548, srcKey: '../assets/extracted/feuillage/feuillage-07-03.png', source: 'source-herbe-05.png' },
  { id: 'feuillage-07-04', label: 'Feuillage 4', family: 'feuillage', width: 114, height: 221, srcKey: '../assets/extracted/feuillage/feuillage-07-04.png', source: 'source-herbe-05.png' },
  { id: 'feuillage-07-05', label: 'Feuillage 5', family: 'feuillage', width: 214, height: 182, srcKey: '../assets/extracted/feuillage/feuillage-07-05.png', source: 'source-herbe-05.png' },
  { id: 'feuillage-07-06', label: 'Feuillage 6', family: 'feuillage', width: 139, height: 129, srcKey: '../assets/extracted/feuillage/feuillage-07-06.png', source: 'source-herbe-05.png' },
  { id: 'feuillage-07-07', label: 'Feuillage 7', family: 'feuillage', width: 235, height: 218, srcKey: '../assets/extracted/feuillage/feuillage-07-07.png', source: 'source-herbe-05.png' },
  { id: 'feuillage-07-08', label: 'Feuillage 8', family: 'feuillage', width: 210, height: 157, srcKey: '../assets/extracted/feuillage/feuillage-07-08.png', source: 'source-herbe-05.png' },
  { id: 'feuillage-07-09', label: 'Feuillage 9', family: 'feuillage', width: 296, height: 175, srcKey: '../assets/extracted/feuillage/feuillage-07-09.png', source: 'source-herbe-05.png' },
  { id: 'feuillage-07-10', label: 'Feuillage 10', family: 'feuillage', width: 223, height: 584, srcKey: '../assets/extracted/feuillage/feuillage-07-10.png', source: 'source-herbe-05.png' },
  { id: 'feuillage-07-11', label: 'Feuillage 11', family: 'feuillage', width: 243, height: 542, srcKey: '../assets/extracted/feuillage/feuillage-07-11.png', source: 'source-herbe-05.png' },
  { id: 'feuillage-07-12', label: 'Feuillage 12', family: 'feuillage', width: 371, height: 269, srcKey: '../assets/extracted/feuillage/feuillage-07-12.png', source: 'source-herbe-05.png' },
  { id: 'feuillage-08-01', label: 'Feuillage 1', family: 'feuillage', width: 288, height: 704, srcKey: '../assets/extracted/feuillage/feuillage-08-01.png', source: 'source-herbe-06.png' },
  { id: 'feuillage-08-02', label: 'Feuillage 2', family: 'feuillage', width: 275, height: 650, srcKey: '../assets/extracted/feuillage/feuillage-08-02.png', source: 'source-herbe-06.png' },
  { id: 'feuillage-08-03', label: 'Feuillage 3', family: 'feuillage', width: 80, height: 90, srcKey: '../assets/extracted/feuillage/feuillage-08-03.png', source: 'source-herbe-06.png' },
  { id: 'feuillage-08-04', label: 'Feuillage 4', family: 'feuillage', width: 353, height: 529, srcKey: '../assets/extracted/feuillage/feuillage-08-04.png', source: 'source-herbe-06.png' },
  { id: 'feuillage-09-01', label: 'Feuillage 1', family: 'feuillage', width: 351, height: 547, srcKey: '../assets/extracted/feuillage/feuillage-09-01.png', source: 'source-herbe-07.png' },
  { id: 'feuillage-09-02', label: 'Feuillage 2', family: 'feuillage', width: 325, height: 560, srcKey: '../assets/extracted/feuillage/feuillage-09-02.png', source: 'source-herbe-07.png' },
  { id: 'feuillage-09-03', label: 'Feuillage 3', family: 'feuillage', width: 309, height: 353, srcKey: '../assets/extracted/feuillage/feuillage-09-03.png', source: 'source-herbe-07.png' },
  { id: 'feuillage-09-04', label: 'Feuillage 4', family: 'feuillage', width: 356, height: 515, srcKey: '../assets/extracted/feuillage/feuillage-09-04.png', source: 'source-herbe-07.png' },
  { id: 'feuillage-09-05', label: 'Feuillage 5', family: 'feuillage', width: 326, height: 485, srcKey: '../assets/extracted/feuillage/feuillage-09-05.png', source: 'source-herbe-07.png' },
  { id: 'feuillage-09-06', label: 'Feuillage 6', family: 'feuillage', width: 310, height: 360, srcKey: '../assets/extracted/feuillage/feuillage-09-06.png', source: 'source-herbe-07.png' },
  { id: 'couronne-10-01', label: 'Couronne 1', family: 'couronne', width: 295, height: 365, srcKey: '../assets/extracted/couronne/couronne-10-01.png', source: 'COURONNE_02.png' },
  { id: 'couronne-10-02', label: 'Couronne 2', family: 'couronne', width: 297, height: 342, srcKey: '../assets/extracted/couronne/couronne-10-02.png', source: 'COURONNE_02.png' },
  { id: 'couronne-10-03', label: 'Couronne 3', family: 'couronne', width: 288, height: 314, srcKey: '../assets/extracted/couronne/couronne-10-03.png', source: 'COURONNE_02.png' },
  { id: 'couronne-10-04', label: 'Couronne 4', family: 'couronne', width: 290, height: 308, srcKey: '../assets/extracted/couronne/couronne-10-04.png', source: 'COURONNE_02.png' },
  { id: 'couronne-10-05', label: 'Couronne 5', family: 'couronne', width: 292, height: 305, srcKey: '../assets/extracted/couronne/couronne-10-05.png', source: 'COURONNE_02.png' },
  { id: 'couronne-10-06', label: 'Couronne 6', family: 'couronne', width: 295, height: 310, srcKey: '../assets/extracted/couronne/couronne-10-06.png', source: 'COURONNE_02.png' },
  { id: 'couronne-10-07', label: 'Couronne 7', family: 'couronne', width: 287, height: 301, srcKey: '../assets/extracted/couronne/couronne-10-07.png', source: 'COURONNE_02.png' },
  { id: 'couronne-10-08', label: 'Couronne 8', family: 'couronne', width: 595, height: 344, srcKey: '../assets/extracted/couronne/couronne-10-08.png', source: 'COURONNE_02.png' },
  { id: 'couronne-10-09', label: 'Couronne 9', family: 'couronne', width: 291, height: 309, srcKey: '../assets/extracted/couronne/couronne-10-09.png', source: 'COURONNE_02.png' },
  { id: 'couronne-10-10', label: 'Couronne 10', family: 'couronne', width: 298, height: 307, srcKey: '../assets/extracted/couronne/couronne-10-10.png', source: 'COURONNE_02.png' },
  { id: 'couronne-10-11', label: 'Couronne 11', family: 'couronne', width: 304, height: 286, srcKey: '../assets/extracted/couronne/couronne-10-11.png', source: 'COURONNE_02.png' },
  { id: 'couronne-10-12', label: 'Couronne 12', family: 'couronne', width: 294, height: 336, srcKey: '../assets/extracted/couronne/couronne-10-12.png', source: 'COURONNE_02.png' },
  { id: 'couronne-10-13', label: 'Couronne 13', family: 'couronne', width: 302, height: 321, srcKey: '../assets/extracted/couronne/couronne-10-13.png', source: 'COURONNE_02.png' },
  { id: 'couronne-10-14', label: 'Couronne 14', family: 'couronne', width: 310, height: 321, srcKey: '../assets/extracted/couronne/couronne-10-14.png', source: 'COURONNE_02.png' },
  { id: 'couronne-10-15', label: 'Couronne 15', family: 'couronne', width: 298, height: 315, srcKey: '../assets/extracted/couronne/couronne-10-15.png', source: 'COURONNE_02.png' },
  { id: 'couronne-10-16', label: 'Couronne 16', family: 'couronne', width: 292, height: 322, srcKey: '../assets/extracted/couronne/couronne-10-16.png', source: 'COURONNE_02.png' },
  { id: 'couronne-10-17', label: 'Couronne 17', family: 'couronne', width: 297, height: 306, srcKey: '../assets/extracted/couronne/couronne-10-17.png', source: 'COURONNE_02.png' },
  { id: 'couronne-10-18', label: 'Couronne 18', family: 'couronne', width: 300, height: 307, srcKey: '../assets/extracted/couronne/couronne-10-18.png', source: 'COURONNE_02.png' },
  { id: 'couronne-10-19', label: 'Couronne 19', family: 'couronne', width: 300, height: 307, srcKey: '../assets/extracted/couronne/couronne-10-19.png', source: 'COURONNE_02.png' },
  { id: 'couronne-10-20', label: 'Couronne 20', family: 'couronne', width: 300, height: 335, srcKey: '../assets/extracted/couronne/couronne-10-20.png', source: 'COURONNE_02.png' },
  { id: 'couronne-10-21', label: 'Couronne 21', family: 'couronne', width: 294, height: 319, srcKey: '../assets/extracted/couronne/couronne-10-21.png', source: 'COURONNE_02.png' },
  { id: 'couronne-10-22', label: 'Couronne 22', family: 'couronne', width: 308, height: 313, srcKey: '../assets/extracted/couronne/couronne-10-22.png', source: 'COURONNE_02.png' },
  { id: 'couronne-10-23', label: 'Couronne 23', family: 'couronne', width: 298, height: 307, srcKey: '../assets/extracted/couronne/couronne-10-23.png', source: 'COURONNE_02.png' },
  { id: 'fleur-11-01', label: 'Fleur 1', family: 'fleur', width: 135, height: 132, srcKey: '../assets/extracted/fleur/fleur-11-01.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-02', label: 'Fleur 2', family: 'fleur', width: 125, height: 127, srcKey: '../assets/extracted/fleur/fleur-11-02.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-03', label: 'Fleur 3', family: 'fleur', width: 135, height: 135, srcKey: '../assets/extracted/fleur/fleur-11-03.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-04', label: 'Fleur 4', family: 'fleur', width: 146, height: 139, srcKey: '../assets/extracted/fleur/fleur-11-04.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-05', label: 'Fleur 5', family: 'fleur', width: 135, height: 142, srcKey: '../assets/extracted/fleur/fleur-11-05.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-06', label: 'Fleur 6', family: 'fleur', width: 128, height: 131, srcKey: '../assets/extracted/fleur/fleur-11-06.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-07', label: 'Fleur 7', family: 'fleur', width: 140, height: 143, srcKey: '../assets/extracted/fleur/fleur-11-07.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-08', label: 'Fleur 8', family: 'fleur', width: 128, height: 133, srcKey: '../assets/extracted/fleur/fleur-11-08.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-09', label: 'Fleur 9', family: 'fleur', width: 142, height: 145, srcKey: '../assets/extracted/fleur/fleur-11-09.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-10', label: 'Fleur 10', family: 'fleur', width: 145, height: 146, srcKey: '../assets/extracted/fleur/fleur-11-10.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-11', label: 'Fleur 11', family: 'fleur', width: 128, height: 131, srcKey: '../assets/extracted/fleur/fleur-11-11.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-12', label: 'Fleur 12', family: 'fleur', width: 133, height: 131, srcKey: '../assets/extracted/fleur/fleur-11-12.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-13', label: 'Fleur 13', family: 'fleur', width: 136, height: 134, srcKey: '../assets/extracted/fleur/fleur-11-13.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-14', label: 'Fleur 14', family: 'fleur', width: 131, height: 132, srcKey: '../assets/extracted/fleur/fleur-11-14.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-15', label: 'Fleur 15', family: 'fleur', width: 148, height: 139, srcKey: '../assets/extracted/fleur/fleur-11-15.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-16', label: 'Fleur 16', family: 'fleur', width: 148, height: 132, srcKey: '../assets/extracted/fleur/fleur-11-16.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-17', label: 'Fleur 17', family: 'fleur', width: 142, height: 136, srcKey: '../assets/extracted/fleur/fleur-11-17.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-18', label: 'Fleur 18', family: 'fleur', width: 136, height: 130, srcKey: '../assets/extracted/fleur/fleur-11-18.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-19', label: 'Fleur 19', family: 'fleur', width: 131, height: 125, srcKey: '../assets/extracted/fleur/fleur-11-19.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-20', label: 'Fleur 20', family: 'fleur', width: 127, height: 111, srcKey: '../assets/extracted/fleur/fleur-11-20.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-21', label: 'Fleur 21', family: 'fleur', width: 151, height: 135, srcKey: '../assets/extracted/fleur/fleur-11-21.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-22', label: 'Fleur 22', family: 'fleur', width: 145, height: 138, srcKey: '../assets/extracted/fleur/fleur-11-22.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-23', label: 'Fleur 23', family: 'fleur', width: 134, height: 133, srcKey: '../assets/extracted/fleur/fleur-11-23.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-24', label: 'Fleur 24', family: 'fleur', width: 136, height: 132, srcKey: '../assets/extracted/fleur/fleur-11-24.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-25', label: 'Fleur 25', family: 'fleur', width: 132, height: 131, srcKey: '../assets/extracted/fleur/fleur-11-25.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-26', label: 'Fleur 26', family: 'fleur', width: 132, height: 131, srcKey: '../assets/extracted/fleur/fleur-11-26.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-27', label: 'Fleur 27', family: 'fleur', width: 127, height: 128, srcKey: '../assets/extracted/fleur/fleur-11-27.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-28', label: 'Fleur 28', family: 'fleur', width: 132, height: 130, srcKey: '../assets/extracted/fleur/fleur-11-28.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-29', label: 'Fleur 29', family: 'fleur', width: 129, height: 136, srcKey: '../assets/extracted/fleur/fleur-11-29.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-30', label: 'Fleur 30', family: 'fleur', width: 147, height: 145, srcKey: '../assets/extracted/fleur/fleur-11-30.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-31', label: 'Fleur 31', family: 'fleur', width: 136, height: 133, srcKey: '../assets/extracted/fleur/fleur-11-31.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-32', label: 'Fleur 32', family: 'fleur', width: 149, height: 142, srcKey: '../assets/extracted/fleur/fleur-11-32.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-33', label: 'Fleur 33', family: 'fleur', width: 143, height: 125, srcKey: '../assets/extracted/fleur/fleur-11-33.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-34', label: 'Fleur 34', family: 'fleur', width: 135, height: 127, srcKey: '../assets/extracted/fleur/fleur-11-34.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-35', label: 'Fleur 35', family: 'fleur', width: 143, height: 141, srcKey: '../assets/extracted/fleur/fleur-11-35.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-36', label: 'Fleur 36', family: 'fleur', width: 141, height: 139, srcKey: '../assets/extracted/fleur/fleur-11-36.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-37', label: 'Fleur 37', family: 'fleur', width: 153, height: 139, srcKey: '../assets/extracted/fleur/fleur-11-37.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-38', label: 'Fleur 38', family: 'fleur', width: 135, height: 134, srcKey: '../assets/extracted/fleur/fleur-11-38.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-39', label: 'Fleur 39', family: 'fleur', width: 138, height: 134, srcKey: '../assets/extracted/fleur/fleur-11-39.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-40', label: 'Fleur 40', family: 'fleur', width: 135, height: 137, srcKey: '../assets/extracted/fleur/fleur-11-40.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-41', label: 'Fleur 41', family: 'fleur', width: 134, height: 130, srcKey: '../assets/extracted/fleur/fleur-11-41.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-42', label: 'Fleur 42', family: 'fleur', width: 148, height: 129, srcKey: '../assets/extracted/fleur/fleur-11-42.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-43', label: 'Fleur 43', family: 'fleur', width: 138, height: 130, srcKey: '../assets/extracted/fleur/fleur-11-43.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-44', label: 'Fleur 44', family: 'fleur', width: 139, height: 125, srcKey: '../assets/extracted/fleur/fleur-11-44.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-45', label: 'Fleur 45', family: 'fleur', width: 136, height: 147, srcKey: '../assets/extracted/fleur/fleur-11-45.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-46', label: 'Fleur 46', family: 'fleur', width: 137, height: 133, srcKey: '../assets/extracted/fleur/fleur-11-46.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-47', label: 'Fleur 47', family: 'fleur', width: 134, height: 127, srcKey: '../assets/extracted/fleur/fleur-11-47.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-48', label: 'Fleur 48', family: 'fleur', width: 137, height: 141, srcKey: '../assets/extracted/fleur/fleur-11-48.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-49', label: 'Fleur 49', family: 'fleur', width: 145, height: 142, srcKey: '../assets/extracted/fleur/fleur-11-49.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-50', label: 'Fleur 50', family: 'fleur', width: 146, height: 133, srcKey: '../assets/extracted/fleur/fleur-11-50.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-51', label: 'Fleur 51', family: 'fleur', width: 141, height: 139, srcKey: '../assets/extracted/fleur/fleur-11-51.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-52', label: 'Fleur 52', family: 'fleur', width: 142, height: 134, srcKey: '../assets/extracted/fleur/fleur-11-52.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-53', label: 'Fleur 53', family: 'fleur', width: 137, height: 129, srcKey: '../assets/extracted/fleur/fleur-11-53.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-54', label: 'Fleur 54', family: 'fleur', width: 129, height: 125, srcKey: '../assets/extracted/fleur/fleur-11-54.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-55', label: 'Fleur 55', family: 'fleur', width: 143, height: 146, srcKey: '../assets/extracted/fleur/fleur-11-55.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-56', label: 'Fleur 56', family: 'fleur', width: 133, height: 124, srcKey: '../assets/extracted/fleur/fleur-11-56.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-57', label: 'Fleur 57', family: 'fleur', width: 126, height: 125, srcKey: '../assets/extracted/fleur/fleur-11-57.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-58', label: 'Fleur 58', family: 'fleur', width: 137, height: 138, srcKey: '../assets/extracted/fleur/fleur-11-58.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-59', label: 'Fleur 59', family: 'fleur', width: 143, height: 137, srcKey: '../assets/extracted/fleur/fleur-11-59.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-60', label: 'Fleur 60', family: 'fleur', width: 133, height: 130, srcKey: '../assets/extracted/fleur/fleur-11-60.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-61', label: 'Fleur 61', family: 'fleur', width: 140, height: 135, srcKey: '../assets/extracted/fleur/fleur-11-61.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-62', label: 'Fleur 62', family: 'fleur', width: 133, height: 132, srcKey: '../assets/extracted/fleur/fleur-11-62.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-63', label: 'Fleur 63', family: 'fleur', width: 142, height: 134, srcKey: '../assets/extracted/fleur/fleur-11-63.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-64', label: 'Fleur 64', family: 'fleur', width: 133, height: 130, srcKey: '../assets/extracted/fleur/fleur-11-64.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-65', label: 'Fleur 65', family: 'fleur', width: 145, height: 135, srcKey: '../assets/extracted/fleur/fleur-11-65.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-66', label: 'Fleur 66', family: 'fleur', width: 141, height: 135, srcKey: '../assets/extracted/fleur/fleur-11-66.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-67', label: 'Fleur 67', family: 'fleur', width: 139, height: 132, srcKey: '../assets/extracted/fleur/fleur-11-67.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-68', label: 'Fleur 68', family: 'fleur', width: 132, height: 125, srcKey: '../assets/extracted/fleur/fleur-11-68.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-69', label: 'Fleur 69', family: 'fleur', width: 131, height: 112, srcKey: '../assets/extracted/fleur/fleur-11-69.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-70', label: 'Fleur 70', family: 'fleur', width: 134, height: 136, srcKey: '../assets/extracted/fleur/fleur-11-70.png', source: 'FLEUR_03.png' },
  { id: 'fleur-11-71', label: 'Fleur 71', family: 'fleur', width: 139, height: 137, srcKey: '../assets/extracted/fleur/fleur-11-71.png', source: 'FLEUR_03.png' },
  { id: 'atmosphere-12-01', label: 'Atmosphere 2', family: 'atmosphere', width: 538, height: 483, srcKey: '../assets/extracted/atmosphere/atmosphere-12-01.png', source: 'atmos2.png' },
] as const;

export const ELEMENTS: ElementAsset[] = manifest.map((item) => ({
  id: item.id, label: item.label, family: item.family, width: item.width, height: item.height, src: assetModules[item.srcKey], source: item.source,
}));

export const ELEMENT_FAMILIES: { id: ElementFamily; label: string }[] = [
  { id: "florale", label: "Fleurs" },
  { id: "fleur", label: "Fleurs (planches)" },
  { id: "couronne", label: "Couronnes" },
  { id: "feuillage", label: "Feuillages" },
  { id: "marin", label: "Marin" },
  { id: "atmosphere", label: "Atmosphères" },
];

export function getElementById(id: string) { return ELEMENTS.find((item) => item.id === id); }