/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishesRouteImport } from './routes/wishes'
import { Route as VitrineRouteImport } from './routes/vitrine'
import { Route as StartRouteImport } from './routes/start'
import { Route as SpaceRouteImport } from './routes/space'
import { Route as PresentationRouteImport } from './routes/presentation'
import { Route as PresenceRouteImport } from './routes/presence'
import { Route as PracticalRouteImport } from './routes/practical'
import { Route as ParcoursRouteImport } from './routes/parcours'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NoWordsRouteImport } from './routes/no-words'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as InspirationRouteImport } from './routes/inspiration'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DatesRouteImport } from './routes/dates'
import { Route as CrisisRouteImport } from './routes/crisis'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as PracticalIndexRouteImport } from './routes/practical.index'
import { Route as HelpIndexRouteImport } from './routes/help.index'
import { Route as GardenIndexRouteImport } from './routes/garden.index'
import { Route as ResourcesCategoryRouteImport } from './routes/resources.$category'
import { Route as PracticalTextsRouteImport } from './routes/practical.texts'
import { Route as PracticalStepsRouteImport } from './routes/practical.steps'
import { Route as PracticalShareRouteImport } from './routes/practical.share'
import { Route as PracticalObjectsRouteImport } from './routes/practical.objects'
import { Route as PracticalFlowersRouteImport } from './routes/practical.flowers'
import { Route as PracticalCeremonyRouteImport } from './routes/practical.ceremony'
import { Route as PracticalBookletRouteImport } from './routes/practical.booklet'
import { Route as PracticalAtmosphereRouteImport } from './routes/practical.atmosphere'
import { Route as HelpCorpsRouteImport } from './routes/help.corps'
import { Route as GardenZoneRouteImport } from './routes/garden.$zone'
import { Route as ComposeZoneRouteImport } from './routes/compose.$zone'
import { Route as ResourcesConfirmProviderIdRouteImport } from './routes/resources.confirm.$providerId'
import { Route as ResourcesCategoryProviderIdRouteImport } from './routes/resources.$category.$providerId'
import { Route as HelpCorpsNuitsRouteImport } from './routes/help.corps.nuits'
import { Route as HelpCorpsMangerRouteImport } from './routes/help.corps.manger'
import { Route as HelpCorpsHabillerRouteImport } from './routes/help.corps.habiller'
import { Route as HelpCorpsEauRouteImport } from './routes/help.corps.eau'
import { Route as ApiPublicSouffleSoundIdRouteImport } from './routes/api/public/souffle-sound.$id'

const WishesRoute = WishesRouteImport.update({
  id: '/wishes',
  path: '/wishes',
  getParentRoute: () => rootRouteImport,
} as any)
const VitrineRoute = VitrineRouteImport.update({
  id: '/vitrine',
  path: '/vitrine',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaceRoute = SpaceRouteImport.update({
  id: '/space',
  path: '/space',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationRoute = PresentationRouteImport.update({
  id: '/presentation',
  path: '/presentation',
  getParentRoute: () => rootRouteImport,
} as any)
const PresenceRoute = PresenceRouteImport.update({
  id: '/presence',
  path: '/presence',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticalRoute = PracticalRouteImport.update({
  id: '/practical',
  path: '/practical',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcoursRoute = ParcoursRouteImport.update({
  id: '/parcours',
  path: '/parcours',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NoWordsRoute = NoWordsRouteImport.update({
  id: '/no-words',
  path: '/no-words',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const InspirationRoute = InspirationRouteImport.update({
  id: '/inspiration',
  path: '/inspiration',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DatesRoute = DatesRouteImport.update({
  id: '/dates',
  path: '/dates',
  getParentRoute: () => rootRouteImport,
} as any)
const CrisisRoute = CrisisRouteImport.update({
  id: '/crisis',
  path: '/crisis',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticalIndexRoute = PracticalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PracticalRoute,
} as any)
const HelpIndexRoute = HelpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HelpRoute,
} as any)
const GardenIndexRoute = GardenIndexRouteImport.update({
  id: '/garden/',
  path: '/garden/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesCategoryRoute = ResourcesCategoryRouteImport.update({
  id: '/resources/$category',
  path: '/resources/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticalTextsRoute = PracticalTextsRouteImport.update({
  id: '/texts',
  path: '/texts',
  getParentRoute: () => PracticalRoute,
} as any)
const PracticalStepsRoute = PracticalStepsRouteImport.update({
  id: '/steps',
  path: '/steps',
  getParentRoute: () => PracticalRoute,
} as any)
const PracticalShareRoute = PracticalShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => PracticalRoute,
} as any)
const PracticalObjectsRoute = PracticalObjectsRouteImport.update({
  id: '/objects',
  path: '/objects',
  getParentRoute: () => PracticalRoute,
} as any)
const PracticalFlowersRoute = PracticalFlowersRouteImport.update({
  id: '/flowers',
  path: '/flowers',
  getParentRoute: () => PracticalRoute,
} as any)
const PracticalCeremonyRoute = PracticalCeremonyRouteImport.update({
  id: '/ceremony',
  path: '/ceremony',
  getParentRoute: () => PracticalRoute,
} as any)
const PracticalBookletRoute = PracticalBookletRouteImport.update({
  id: '/booklet',
  path: '/booklet',
  getParentRoute: () => PracticalRoute,
} as any)
const PracticalAtmosphereRoute = PracticalAtmosphereRouteImport.update({
  id: '/atmosphere',
  path: '/atmosphere',
  getParentRoute: () => PracticalRoute,
} as any)
const HelpCorpsRoute = HelpCorpsRouteImport.update({
  id: '/corps',
  path: '/corps',
  getParentRoute: () => HelpRoute,
} as any)
const GardenZoneRoute = GardenZoneRouteImport.update({
  id: '/garden/$zone',
  path: '/garden/$zone',
  getParentRoute: () => rootRouteImport,
} as any)
const ComposeZoneRoute = ComposeZoneRouteImport.update({
  id: '/compose/$zone',
  path: '/compose/$zone',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesConfirmProviderIdRoute =
  ResourcesConfirmProviderIdRouteImport.update({
    id: '/resources/confirm/$providerId',
    path: '/resources/confirm/$providerId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResourcesCategoryProviderIdRoute =
  ResourcesCategoryProviderIdRouteImport.update({
    id: '/$providerId',
    path: '/$providerId',
    getParentRoute: () => ResourcesCategoryRoute,
  } as any)
const HelpCorpsNuitsRoute = HelpCorpsNuitsRouteImport.update({
  id: '/nuits',
  path: '/nuits',
  getParentRoute: () => HelpCorpsRoute,
} as any)
const HelpCorpsMangerRoute = HelpCorpsMangerRouteImport.update({
  id: '/manger',
  path: '/manger',
  getParentRoute: () => HelpCorpsRoute,
} as any)
const HelpCorpsHabillerRoute = HelpCorpsHabillerRouteImport.update({
  id: '/habiller',
  path: '/habiller',
  getParentRoute: () => HelpCorpsRoute,
} as any)
const HelpCorpsEauRoute = HelpCorpsEauRouteImport.update({
  id: '/eau',
  path: '/eau',
  getParentRoute: () => HelpCorpsRoute,
} as any)
const ApiPublicSouffleSoundIdRoute = ApiPublicSouffleSoundIdRouteImport.update({
  id: '/api/public/souffle-sound/$id',
  path: '/api/public/souffle-sound/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/crisis': typeof CrisisRoute
  '/dates': typeof DatesRoute
  '/help': typeof HelpRouteWithChildren
  '/home': typeof HomeRoute
  '/inspiration': typeof InspirationRoute
  '/journal': typeof JournalRoute
  '/memories': typeof MemoriesRoute
  '/no-words': typeof NoWordsRoute
  '/onboarding': typeof OnboardingRoute
  '/parcours': typeof ParcoursRoute
  '/practical': typeof PracticalRouteWithChildren
  '/presence': typeof PresenceRoute
  '/presentation': typeof PresentationRoute
  '/space': typeof SpaceRoute
  '/start': typeof StartRoute
  '/vitrine': typeof VitrineRoute
  '/wishes': typeof WishesRoute
  '/compose/$zone': typeof ComposeZoneRoute
  '/garden/$zone': typeof GardenZoneRoute
  '/help/corps': typeof HelpCorpsRouteWithChildren
  '/practical/atmosphere': typeof PracticalAtmosphereRoute
  '/practical/booklet': typeof PracticalBookletRoute
  '/practical/ceremony': typeof PracticalCeremonyRoute
  '/practical/flowers': typeof PracticalFlowersRoute
  '/practical/objects': typeof PracticalObjectsRoute
  '/practical/share': typeof PracticalShareRoute
  '/practical/steps': typeof PracticalStepsRoute
  '/practical/texts': typeof PracticalTextsRoute
  '/resources/$category': typeof ResourcesCategoryRouteWithChildren
  '/garden/': typeof GardenIndexRoute
  '/help/': typeof HelpIndexRoute
  '/practical/': typeof PracticalIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/help/corps/eau': typeof HelpCorpsEauRoute
  '/help/corps/habiller': typeof HelpCorpsHabillerRoute
  '/help/corps/manger': typeof HelpCorpsMangerRoute
  '/help/corps/nuits': typeof HelpCorpsNuitsRoute
  '/resources/$category/$providerId': typeof ResourcesCategoryProviderIdRoute
  '/resources/confirm/$providerId': typeof ResourcesConfirmProviderIdRoute
  '/api/public/souffle-sound/$id': typeof ApiPublicSouffleSoundIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/crisis': typeof CrisisRoute
  '/dates': typeof DatesRoute
  '/home': typeof HomeRoute
  '/inspiration': typeof InspirationRoute
  '/journal': typeof JournalRoute
  '/memories': typeof MemoriesRoute
  '/no-words': typeof NoWordsRoute
  '/onboarding': typeof OnboardingRoute
  '/parcours': typeof ParcoursRoute
  '/presence': typeof PresenceRoute
  '/presentation': typeof PresentationRoute
  '/space': typeof SpaceRoute
  '/start': typeof StartRoute
  '/vitrine': typeof VitrineRoute
  '/wishes': typeof WishesRoute
  '/compose/$zone': typeof ComposeZoneRoute
  '/garden/$zone': typeof GardenZoneRoute
  '/help/corps': typeof HelpCorpsRouteWithChildren
  '/practical/atmosphere': typeof PracticalAtmosphereRoute
  '/practical/booklet': typeof PracticalBookletRoute
  '/practical/ceremony': typeof PracticalCeremonyRoute
  '/practical/flowers': typeof PracticalFlowersRoute
  '/practical/objects': typeof PracticalObjectsRoute
  '/practical/share': typeof PracticalShareRoute
  '/practical/steps': typeof PracticalStepsRoute
  '/practical/texts': typeof PracticalTextsRoute
  '/resources/$category': typeof ResourcesCategoryRouteWithChildren
  '/garden': typeof GardenIndexRoute
  '/help': typeof HelpIndexRoute
  '/practical': typeof PracticalIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/help/corps/eau': typeof HelpCorpsEauRoute
  '/help/corps/habiller': typeof HelpCorpsHabillerRoute
  '/help/corps/manger': typeof HelpCorpsMangerRoute
  '/help/corps/nuits': typeof HelpCorpsNuitsRoute
  '/resources/$category/$providerId': typeof ResourcesCategoryProviderIdRoute
  '/resources/confirm/$providerId': typeof ResourcesConfirmProviderIdRoute
  '/api/public/souffle-sound/$id': typeof ApiPublicSouffleSoundIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/crisis': typeof CrisisRoute
  '/dates': typeof DatesRoute
  '/help': typeof HelpRouteWithChildren
  '/home': typeof HomeRoute
  '/inspiration': typeof InspirationRoute
  '/journal': typeof JournalRoute
  '/memories': typeof MemoriesRoute
  '/no-words': typeof NoWordsRoute
  '/onboarding': typeof OnboardingRoute
  '/parcours': typeof ParcoursRoute
  '/practical': typeof PracticalRouteWithChildren
  '/presence': typeof PresenceRoute
  '/presentation': typeof PresentationRoute
  '/space': typeof SpaceRoute
  '/start': typeof StartRoute
  '/vitrine': typeof VitrineRoute
  '/wishes': typeof WishesRoute
  '/compose/$zone': typeof ComposeZoneRoute
  '/garden/$zone': typeof GardenZoneRoute
  '/help/corps': typeof HelpCorpsRouteWithChildren
  '/practical/atmosphere': typeof PracticalAtmosphereRoute
  '/practical/booklet': typeof PracticalBookletRoute
  '/practical/ceremony': typeof PracticalCeremonyRoute
  '/practical/flowers': typeof PracticalFlowersRoute
  '/practical/objects': typeof PracticalObjectsRoute
  '/practical/share': typeof PracticalShareRoute
  '/practical/steps': typeof PracticalStepsRoute
  '/practical/texts': typeof PracticalTextsRoute
  '/resources/$category': typeof ResourcesCategoryRouteWithChildren
  '/garden/': typeof GardenIndexRoute
  '/help/': typeof HelpIndexRoute
  '/practical/': typeof PracticalIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/help/corps/eau': typeof HelpCorpsEauRoute
  '/help/corps/habiller': typeof HelpCorpsHabillerRoute
  '/help/corps/manger': typeof HelpCorpsMangerRoute
  '/help/corps/nuits': typeof HelpCorpsNuitsRoute
  '/resources/$category/$providerId': typeof ResourcesCategoryProviderIdRoute
  '/resources/confirm/$providerId': typeof ResourcesConfirmProviderIdRoute
  '/api/public/souffle-sound/$id': typeof ApiPublicSouffleSoundIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community'
    | '/crisis'
    | '/dates'
    | '/help'
    | '/home'
    | '/inspiration'
    | '/journal'
    | '/memories'
    | '/no-words'
    | '/onboarding'
    | '/parcours'
    | '/practical'
    | '/presence'
    | '/presentation'
    | '/space'
    | '/start'
    | '/vitrine'
    | '/wishes'
    | '/compose/$zone'
    | '/garden/$zone'
    | '/help/corps'
    | '/practical/atmosphere'
    | '/practical/booklet'
    | '/practical/ceremony'
    | '/practical/flowers'
    | '/practical/objects'
    | '/practical/share'
    | '/practical/steps'
    | '/practical/texts'
    | '/resources/$category'
    | '/garden/'
    | '/help/'
    | '/practical/'
    | '/resources/'
    | '/help/corps/eau'
    | '/help/corps/habiller'
    | '/help/corps/manger'
    | '/help/corps/nuits'
    | '/resources/$category/$providerId'
    | '/resources/confirm/$providerId'
    | '/api/public/souffle-sound/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/crisis'
    | '/dates'
    | '/home'
    | '/inspiration'
    | '/journal'
    | '/memories'
    | '/no-words'
    | '/onboarding'
    | '/parcours'
    | '/presence'
    | '/presentation'
    | '/space'
    | '/start'
    | '/vitrine'
    | '/wishes'
    | '/compose/$zone'
    | '/garden/$zone'
    | '/help/corps'
    | '/practical/atmosphere'
    | '/practical/booklet'
    | '/practical/ceremony'
    | '/practical/flowers'
    | '/practical/objects'
    | '/practical/share'
    | '/practical/steps'
    | '/practical/texts'
    | '/resources/$category'
    | '/garden'
    | '/help'
    | '/practical'
    | '/resources'
    | '/help/corps/eau'
    | '/help/corps/habiller'
    | '/help/corps/manger'
    | '/help/corps/nuits'
    | '/resources/$category/$providerId'
    | '/resources/confirm/$providerId'
    | '/api/public/souffle-sound/$id'
  id:
    | '__root__'
    | '/'
    | '/community'
    | '/crisis'
    | '/dates'
    | '/help'
    | '/home'
    | '/inspiration'
    | '/journal'
    | '/memories'
    | '/no-words'
    | '/onboarding'
    | '/parcours'
    | '/practical'
    | '/presence'
    | '/presentation'
    | '/space'
    | '/start'
    | '/vitrine'
    | '/wishes'
    | '/compose/$zone'
    | '/garden/$zone'
    | '/help/corps'
    | '/practical/atmosphere'
    | '/practical/booklet'
    | '/practical/ceremony'
    | '/practical/flowers'
    | '/practical/objects'
    | '/practical/share'
    | '/practical/steps'
    | '/practical/texts'
    | '/resources/$category'
    | '/garden/'
    | '/help/'
    | '/practical/'
    | '/resources/'
    | '/help/corps/eau'
    | '/help/corps/habiller'
    | '/help/corps/manger'
    | '/help/corps/nuits'
    | '/resources/$category/$providerId'
    | '/resources/confirm/$providerId'
    | '/api/public/souffle-sound/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityRoute: typeof CommunityRoute
  CrisisRoute: typeof CrisisRoute
  DatesRoute: typeof DatesRoute
  HelpRoute: typeof HelpRouteWithChildren
  HomeRoute: typeof HomeRoute
  InspirationRoute: typeof InspirationRoute
  JournalRoute: typeof JournalRoute
  MemoriesRoute: typeof MemoriesRoute
  NoWordsRoute: typeof NoWordsRoute
  OnboardingRoute: typeof OnboardingRoute
  ParcoursRoute: typeof ParcoursRoute
  PracticalRoute: typeof PracticalRouteWithChildren
  PresenceRoute: typeof PresenceRoute
  PresentationRoute: typeof PresentationRoute
  SpaceRoute: typeof SpaceRoute
  StartRoute: typeof StartRoute
  VitrineRoute: typeof VitrineRoute
  WishesRoute: typeof WishesRoute
  ComposeZoneRoute: typeof ComposeZoneRoute
  GardenZoneRoute: typeof GardenZoneRoute
  ResourcesCategoryRoute: typeof ResourcesCategoryRouteWithChildren
  GardenIndexRoute: typeof GardenIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  ResourcesConfirmProviderIdRoute: typeof ResourcesConfirmProviderIdRoute
  ApiPublicSouffleSoundIdRoute: typeof ApiPublicSouffleSoundIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishes': {
      id: '/wishes'
      path: '/wishes'
      fullPath: '/wishes'
      preLoaderRoute: typeof WishesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vitrine': {
      id: '/vitrine'
      path: '/vitrine'
      fullPath: '/vitrine'
      preLoaderRoute: typeof VitrineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/space': {
      id: '/space'
      path: '/space'
      fullPath: '/space'
      preLoaderRoute: typeof SpaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentation': {
      id: '/presentation'
      path: '/presentation'
      fullPath: '/presentation'
      preLoaderRoute: typeof PresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presence': {
      id: '/presence'
      path: '/presence'
      fullPath: '/presence'
      preLoaderRoute: typeof PresenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practical': {
      id: '/practical'
      path: '/practical'
      fullPath: '/practical'
      preLoaderRoute: typeof PracticalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcours': {
      id: '/parcours'
      path: '/parcours'
      fullPath: '/parcours'
      preLoaderRoute: typeof ParcoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-words': {
      id: '/no-words'
      path: '/no-words'
      fullPath: '/no-words'
      preLoaderRoute: typeof NoWordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspiration': {
      id: '/inspiration'
      path: '/inspiration'
      fullPath: '/inspiration'
      preLoaderRoute: typeof InspirationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dates': {
      id: '/dates'
      path: '/dates'
      fullPath: '/dates'
      preLoaderRoute: typeof DatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crisis': {
      id: '/crisis'
      path: '/crisis'
      fullPath: '/crisis'
      preLoaderRoute: typeof CrisisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practical/': {
      id: '/practical/'
      path: '/'
      fullPath: '/practical/'
      preLoaderRoute: typeof PracticalIndexRouteImport
      parentRoute: typeof PracticalRoute
    }
    '/help/': {
      id: '/help/'
      path: '/'
      fullPath: '/help/'
      preLoaderRoute: typeof HelpIndexRouteImport
      parentRoute: typeof HelpRoute
    }
    '/garden/': {
      id: '/garden/'
      path: '/garden'
      fullPath: '/garden/'
      preLoaderRoute: typeof GardenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$category': {
      id: '/resources/$category'
      path: '/resources/$category'
      fullPath: '/resources/$category'
      preLoaderRoute: typeof ResourcesCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practical/texts': {
      id: '/practical/texts'
      path: '/texts'
      fullPath: '/practical/texts'
      preLoaderRoute: typeof PracticalTextsRouteImport
      parentRoute: typeof PracticalRoute
    }
    '/practical/steps': {
      id: '/practical/steps'
      path: '/steps'
      fullPath: '/practical/steps'
      preLoaderRoute: typeof PracticalStepsRouteImport
      parentRoute: typeof PracticalRoute
    }
    '/practical/share': {
      id: '/practical/share'
      path: '/share'
      fullPath: '/practical/share'
      preLoaderRoute: typeof PracticalShareRouteImport
      parentRoute: typeof PracticalRoute
    }
    '/practical/objects': {
      id: '/practical/objects'
      path: '/objects'
      fullPath: '/practical/objects'
      preLoaderRoute: typeof PracticalObjectsRouteImport
      parentRoute: typeof PracticalRoute
    }
    '/practical/flowers': {
      id: '/practical/flowers'
      path: '/flowers'
      fullPath: '/practical/flowers'
      preLoaderRoute: typeof PracticalFlowersRouteImport
      parentRoute: typeof PracticalRoute
    }
    '/practical/ceremony': {
      id: '/practical/ceremony'
      path: '/ceremony'
      fullPath: '/practical/ceremony'
      preLoaderRoute: typeof PracticalCeremonyRouteImport
      parentRoute: typeof PracticalRoute
    }
    '/practical/booklet': {
      id: '/practical/booklet'
      path: '/booklet'
      fullPath: '/practical/booklet'
      preLoaderRoute: typeof PracticalBookletRouteImport
      parentRoute: typeof PracticalRoute
    }
    '/practical/atmosphere': {
      id: '/practical/atmosphere'
      path: '/atmosphere'
      fullPath: '/practical/atmosphere'
      preLoaderRoute: typeof PracticalAtmosphereRouteImport
      parentRoute: typeof PracticalRoute
    }
    '/help/corps': {
      id: '/help/corps'
      path: '/corps'
      fullPath: '/help/corps'
      preLoaderRoute: typeof HelpCorpsRouteImport
      parentRoute: typeof HelpRoute
    }
    '/garden/$zone': {
      id: '/garden/$zone'
      path: '/garden/$zone'
      fullPath: '/garden/$zone'
      preLoaderRoute: typeof GardenZoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compose/$zone': {
      id: '/compose/$zone'
      path: '/compose/$zone'
      fullPath: '/compose/$zone'
      preLoaderRoute: typeof ComposeZoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/confirm/$providerId': {
      id: '/resources/confirm/$providerId'
      path: '/resources/confirm/$providerId'
      fullPath: '/resources/confirm/$providerId'
      preLoaderRoute: typeof ResourcesConfirmProviderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$category/$providerId': {
      id: '/resources/$category/$providerId'
      path: '/$providerId'
      fullPath: '/resources/$category/$providerId'
      preLoaderRoute: typeof ResourcesCategoryProviderIdRouteImport
      parentRoute: typeof ResourcesCategoryRoute
    }
    '/help/corps/nuits': {
      id: '/help/corps/nuits'
      path: '/nuits'
      fullPath: '/help/corps/nuits'
      preLoaderRoute: typeof HelpCorpsNuitsRouteImport
      parentRoute: typeof HelpCorpsRoute
    }
    '/help/corps/manger': {
      id: '/help/corps/manger'
      path: '/manger'
      fullPath: '/help/corps/manger'
      preLoaderRoute: typeof HelpCorpsMangerRouteImport
      parentRoute: typeof HelpCorpsRoute
    }
    '/help/corps/habiller': {
      id: '/help/corps/habiller'
      path: '/habiller'
      fullPath: '/help/corps/habiller'
      preLoaderRoute: typeof HelpCorpsHabillerRouteImport
      parentRoute: typeof HelpCorpsRoute
    }
    '/help/corps/eau': {
      id: '/help/corps/eau'
      path: '/eau'
      fullPath: '/help/corps/eau'
      preLoaderRoute: typeof HelpCorpsEauRouteImport
      parentRoute: typeof HelpCorpsRoute
    }
    '/api/public/souffle-sound/$id': {
      id: '/api/public/souffle-sound/$id'
      path: '/api/public/souffle-sound/$id'
      fullPath: '/api/public/souffle-sound/$id'
      preLoaderRoute: typeof ApiPublicSouffleSoundIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HelpCorpsRouteChildren {
  HelpCorpsEauRoute: typeof HelpCorpsEauRoute
  HelpCorpsHabillerRoute: typeof HelpCorpsHabillerRoute
  HelpCorpsMangerRoute: typeof HelpCorpsMangerRoute
  HelpCorpsNuitsRoute: typeof HelpCorpsNuitsRoute
}

const HelpCorpsRouteChildren: HelpCorpsRouteChildren = {
  HelpCorpsEauRoute: HelpCorpsEauRoute,
  HelpCorpsHabillerRoute: HelpCorpsHabillerRoute,
  HelpCorpsMangerRoute: HelpCorpsMangerRoute,
  HelpCorpsNuitsRoute: HelpCorpsNuitsRoute,
}

const HelpCorpsRouteWithChildren = HelpCorpsRoute._addFileChildren(
  HelpCorpsRouteChildren,
)

interface HelpRouteChildren {
  HelpCorpsRoute: typeof HelpCorpsRouteWithChildren
  HelpIndexRoute: typeof HelpIndexRoute
}

const HelpRouteChildren: HelpRouteChildren = {
  HelpCorpsRoute: HelpCorpsRouteWithChildren,
  HelpIndexRoute: HelpIndexRoute,
}

const HelpRouteWithChildren = HelpRoute._addFileChildren(HelpRouteChildren)

interface PracticalRouteChildren {
  PracticalAtmosphereRoute: typeof PracticalAtmosphereRoute
  PracticalBookletRoute: typeof PracticalBookletRoute
  PracticalCeremonyRoute: typeof PracticalCeremonyRoute
  PracticalFlowersRoute: typeof PracticalFlowersRoute
  PracticalObjectsRoute: typeof PracticalObjectsRoute
  PracticalShareRoute: typeof PracticalShareRoute
  PracticalStepsRoute: typeof PracticalStepsRoute
  PracticalTextsRoute: typeof PracticalTextsRoute
  PracticalIndexRoute: typeof PracticalIndexRoute
}

const PracticalRouteChildren: PracticalRouteChildren = {
  PracticalAtmosphereRoute: PracticalAtmosphereRoute,
  PracticalBookletRoute: PracticalBookletRoute,
  PracticalCeremonyRoute: PracticalCeremonyRoute,
  PracticalFlowersRoute: PracticalFlowersRoute,
  PracticalObjectsRoute: PracticalObjectsRoute,
  PracticalShareRoute: PracticalShareRoute,
  PracticalStepsRoute: PracticalStepsRoute,
  PracticalTextsRoute: PracticalTextsRoute,
  PracticalIndexRoute: PracticalIndexRoute,
}

const PracticalRouteWithChildren = PracticalRoute._addFileChildren(
  PracticalRouteChildren,
)

interface ResourcesCategoryRouteChildren {
  ResourcesCategoryProviderIdRoute: typeof ResourcesCategoryProviderIdRoute
}

const ResourcesCategoryRouteChildren: ResourcesCategoryRouteChildren = {
  ResourcesCategoryProviderIdRoute: ResourcesCategoryProviderIdRoute,
}

const ResourcesCategoryRouteWithChildren =
  ResourcesCategoryRoute._addFileChildren(ResourcesCategoryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityRoute: CommunityRoute,
  CrisisRoute: CrisisRoute,
  DatesRoute: DatesRoute,
  HelpRoute: HelpRouteWithChildren,
  HomeRoute: HomeRoute,
  InspirationRoute: InspirationRoute,
  JournalRoute: JournalRoute,
  MemoriesRoute: MemoriesRoute,
  NoWordsRoute: NoWordsRoute,
  OnboardingRoute: OnboardingRoute,
  ParcoursRoute: ParcoursRoute,
  PracticalRoute: PracticalRouteWithChildren,
  PresenceRoute: PresenceRoute,
  PresentationRoute: PresentationRoute,
  SpaceRoute: SpaceRoute,
  StartRoute: StartRoute,
  VitrineRoute: VitrineRoute,
  WishesRoute: WishesRoute,
  ComposeZoneRoute: ComposeZoneRoute,
  GardenZoneRoute: GardenZoneRoute,
  ResourcesCategoryRoute: ResourcesCategoryRouteWithChildren,
  GardenIndexRoute: GardenIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  ResourcesConfirmProviderIdRoute: ResourcesConfirmProviderIdRoute,
  ApiPublicSouffleSoundIdRoute: ApiPublicSouffleSoundIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
