/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishesRouteImport } from './routes/wishes'
import { Route as SpaceRouteImport } from './routes/space'
import { Route as PresenceRouteImport } from './routes/presence'
import { Route as PracticalRouteImport } from './routes/practical'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as InspirationRouteImport } from './routes/inspiration'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DatesRouteImport } from './routes/dates'
import { Route as CrisisRouteImport } from './routes/crisis'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PracticalIndexRouteImport } from './routes/practical.index'
import { Route as GardenIndexRouteImport } from './routes/garden.index'
import { Route as PracticalTextsRouteImport } from './routes/practical.texts'
import { Route as PracticalStepsRouteImport } from './routes/practical.steps'
import { Route as PracticalShareRouteImport } from './routes/practical.share'
import { Route as PracticalObjectsRouteImport } from './routes/practical.objects'
import { Route as PracticalFlowersRouteImport } from './routes/practical.flowers'
import { Route as PracticalCeremonyRouteImport } from './routes/practical.ceremony'
import { Route as PracticalBookletRouteImport } from './routes/practical.booklet'
import { Route as PracticalAtmosphereRouteImport } from './routes/practical.atmosphere'
import { Route as GardenZoneRouteImport } from './routes/garden.$zone'
import { Route as ComposeZoneRouteImport } from './routes/compose.$zone'

const WishesRoute = WishesRouteImport.update({
  id: '/wishes',
  path: '/wishes',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaceRoute = SpaceRouteImport.update({
  id: '/space',
  path: '/space',
  getParentRoute: () => rootRouteImport,
} as any)
const PresenceRoute = PresenceRouteImport.update({
  id: '/presence',
  path: '/presence',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticalRoute = PracticalRouteImport.update({
  id: '/practical',
  path: '/practical',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const InspirationRoute = InspirationRouteImport.update({
  id: '/inspiration',
  path: '/inspiration',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DatesRoute = DatesRouteImport.update({
  id: '/dates',
  path: '/dates',
  getParentRoute: () => rootRouteImport,
} as any)
const CrisisRoute = CrisisRouteImport.update({
  id: '/crisis',
  path: '/crisis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticalIndexRoute = PracticalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PracticalRoute,
} as any)
const GardenIndexRoute = GardenIndexRouteImport.update({
  id: '/garden/',
  path: '/garden/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticalTextsRoute = PracticalTextsRouteImport.update({
  id: '/texts',
  path: '/texts',
  getParentRoute: () => PracticalRoute,
} as any)
const PracticalStepsRoute = PracticalStepsRouteImport.update({
  id: '/steps',
  path: '/steps',
  getParentRoute: () => PracticalRoute,
} as any)
const PracticalShareRoute = PracticalShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => PracticalRoute,
} as any)
const PracticalObjectsRoute = PracticalObjectsRouteImport.update({
  id: '/objects',
  path: '/objects',
  getParentRoute: () => PracticalRoute,
} as any)
const PracticalFlowersRoute = PracticalFlowersRouteImport.update({
  id: '/flowers',
  path: '/flowers',
  getParentRoute: () => PracticalRoute,
} as any)
const PracticalCeremonyRoute = PracticalCeremonyRouteImport.update({
  id: '/ceremony',
  path: '/ceremony',
  getParentRoute: () => PracticalRoute,
} as any)
const PracticalBookletRoute = PracticalBookletRouteImport.update({
  id: '/booklet',
  path: '/booklet',
  getParentRoute: () => PracticalRoute,
} as any)
const PracticalAtmosphereRoute = PracticalAtmosphereRouteImport.update({
  id: '/atmosphere',
  path: '/atmosphere',
  getParentRoute: () => PracticalRoute,
} as any)
const GardenZoneRoute = GardenZoneRouteImport.update({
  id: '/garden/$zone',
  path: '/garden/$zone',
  getParentRoute: () => rootRouteImport,
} as any)
const ComposeZoneRoute = ComposeZoneRouteImport.update({
  id: '/compose/$zone',
  path: '/compose/$zone',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crisis': typeof CrisisRoute
  '/dates': typeof DatesRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/inspiration': typeof InspirationRoute
  '/journal': typeof JournalRoute
  '/memories': typeof MemoriesRoute
  '/onboarding': typeof OnboardingRoute
  '/practical': typeof PracticalRouteWithChildren
  '/presence': typeof PresenceRoute
  '/space': typeof SpaceRoute
  '/wishes': typeof WishesRoute
  '/compose/$zone': typeof ComposeZoneRoute
  '/garden/$zone': typeof GardenZoneRoute
  '/practical/atmosphere': typeof PracticalAtmosphereRoute
  '/practical/booklet': typeof PracticalBookletRoute
  '/practical/ceremony': typeof PracticalCeremonyRoute
  '/practical/flowers': typeof PracticalFlowersRoute
  '/practical/objects': typeof PracticalObjectsRoute
  '/practical/share': typeof PracticalShareRoute
  '/practical/steps': typeof PracticalStepsRoute
  '/practical/texts': typeof PracticalTextsRoute
  '/garden/': typeof GardenIndexRoute
  '/practical/': typeof PracticalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crisis': typeof CrisisRoute
  '/dates': typeof DatesRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/inspiration': typeof InspirationRoute
  '/journal': typeof JournalRoute
  '/memories': typeof MemoriesRoute
  '/onboarding': typeof OnboardingRoute
  '/presence': typeof PresenceRoute
  '/space': typeof SpaceRoute
  '/wishes': typeof WishesRoute
  '/compose/$zone': typeof ComposeZoneRoute
  '/garden/$zone': typeof GardenZoneRoute
  '/practical/atmosphere': typeof PracticalAtmosphereRoute
  '/practical/booklet': typeof PracticalBookletRoute
  '/practical/ceremony': typeof PracticalCeremonyRoute
  '/practical/flowers': typeof PracticalFlowersRoute
  '/practical/objects': typeof PracticalObjectsRoute
  '/practical/share': typeof PracticalShareRoute
  '/practical/steps': typeof PracticalStepsRoute
  '/practical/texts': typeof PracticalTextsRoute
  '/garden': typeof GardenIndexRoute
  '/practical': typeof PracticalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crisis': typeof CrisisRoute
  '/dates': typeof DatesRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/inspiration': typeof InspirationRoute
  '/journal': typeof JournalRoute
  '/memories': typeof MemoriesRoute
  '/onboarding': typeof OnboardingRoute
  '/practical': typeof PracticalRouteWithChildren
  '/presence': typeof PresenceRoute
  '/space': typeof SpaceRoute
  '/wishes': typeof WishesRoute
  '/compose/$zone': typeof ComposeZoneRoute
  '/garden/$zone': typeof GardenZoneRoute
  '/practical/atmosphere': typeof PracticalAtmosphereRoute
  '/practical/booklet': typeof PracticalBookletRoute
  '/practical/ceremony': typeof PracticalCeremonyRoute
  '/practical/flowers': typeof PracticalFlowersRoute
  '/practical/objects': typeof PracticalObjectsRoute
  '/practical/share': typeof PracticalShareRoute
  '/practical/steps': typeof PracticalStepsRoute
  '/practical/texts': typeof PracticalTextsRoute
  '/garden/': typeof GardenIndexRoute
  '/practical/': typeof PracticalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crisis'
    | '/dates'
    | '/help'
    | '/home'
    | '/inspiration'
    | '/journal'
    | '/memories'
    | '/onboarding'
    | '/practical'
    | '/presence'
    | '/space'
    | '/wishes'
    | '/compose/$zone'
    | '/garden/$zone'
    | '/practical/atmosphere'
    | '/practical/booklet'
    | '/practical/ceremony'
    | '/practical/flowers'
    | '/practical/objects'
    | '/practical/share'
    | '/practical/steps'
    | '/practical/texts'
    | '/garden/'
    | '/practical/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crisis'
    | '/dates'
    | '/help'
    | '/home'
    | '/inspiration'
    | '/journal'
    | '/memories'
    | '/onboarding'
    | '/presence'
    | '/space'
    | '/wishes'
    | '/compose/$zone'
    | '/garden/$zone'
    | '/practical/atmosphere'
    | '/practical/booklet'
    | '/practical/ceremony'
    | '/practical/flowers'
    | '/practical/objects'
    | '/practical/share'
    | '/practical/steps'
    | '/practical/texts'
    | '/garden'
    | '/practical'
  id:
    | '__root__'
    | '/'
    | '/crisis'
    | '/dates'
    | '/help'
    | '/home'
    | '/inspiration'
    | '/journal'
    | '/memories'
    | '/onboarding'
    | '/practical'
    | '/presence'
    | '/space'
    | '/wishes'
    | '/compose/$zone'
    | '/garden/$zone'
    | '/practical/atmosphere'
    | '/practical/booklet'
    | '/practical/ceremony'
    | '/practical/flowers'
    | '/practical/objects'
    | '/practical/share'
    | '/practical/steps'
    | '/practical/texts'
    | '/garden/'
    | '/practical/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrisisRoute: typeof CrisisRoute
  DatesRoute: typeof DatesRoute
  HelpRoute: typeof HelpRoute
  HomeRoute: typeof HomeRoute
  InspirationRoute: typeof InspirationRoute
  JournalRoute: typeof JournalRoute
  MemoriesRoute: typeof MemoriesRoute
  OnboardingRoute: typeof OnboardingRoute
  PracticalRoute: typeof PracticalRouteWithChildren
  PresenceRoute: typeof PresenceRoute
  SpaceRoute: typeof SpaceRoute
  WishesRoute: typeof WishesRoute
  ComposeZoneRoute: typeof ComposeZoneRoute
  GardenZoneRoute: typeof GardenZoneRoute
  GardenIndexRoute: typeof GardenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishes': {
      id: '/wishes'
      path: '/wishes'
      fullPath: '/wishes'
      preLoaderRoute: typeof WishesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/space': {
      id: '/space'
      path: '/space'
      fullPath: '/space'
      preLoaderRoute: typeof SpaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presence': {
      id: '/presence'
      path: '/presence'
      fullPath: '/presence'
      preLoaderRoute: typeof PresenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practical': {
      id: '/practical'
      path: '/practical'
      fullPath: '/practical'
      preLoaderRoute: typeof PracticalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspiration': {
      id: '/inspiration'
      path: '/inspiration'
      fullPath: '/inspiration'
      preLoaderRoute: typeof InspirationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dates': {
      id: '/dates'
      path: '/dates'
      fullPath: '/dates'
      preLoaderRoute: typeof DatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crisis': {
      id: '/crisis'
      path: '/crisis'
      fullPath: '/crisis'
      preLoaderRoute: typeof CrisisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practical/': {
      id: '/practical/'
      path: '/'
      fullPath: '/practical/'
      preLoaderRoute: typeof PracticalIndexRouteImport
      parentRoute: typeof PracticalRoute
    }
    '/garden/': {
      id: '/garden/'
      path: '/garden'
      fullPath: '/garden/'
      preLoaderRoute: typeof GardenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practical/texts': {
      id: '/practical/texts'
      path: '/texts'
      fullPath: '/practical/texts'
      preLoaderRoute: typeof PracticalTextsRouteImport
      parentRoute: typeof PracticalRoute
    }
    '/practical/steps': {
      id: '/practical/steps'
      path: '/steps'
      fullPath: '/practical/steps'
      preLoaderRoute: typeof PracticalStepsRouteImport
      parentRoute: typeof PracticalRoute
    }
    '/practical/share': {
      id: '/practical/share'
      path: '/share'
      fullPath: '/practical/share'
      preLoaderRoute: typeof PracticalShareRouteImport
      parentRoute: typeof PracticalRoute
    }
    '/practical/objects': {
      id: '/practical/objects'
      path: '/objects'
      fullPath: '/practical/objects'
      preLoaderRoute: typeof PracticalObjectsRouteImport
      parentRoute: typeof PracticalRoute
    }
    '/practical/flowers': {
      id: '/practical/flowers'
      path: '/flowers'
      fullPath: '/practical/flowers'
      preLoaderRoute: typeof PracticalFlowersRouteImport
      parentRoute: typeof PracticalRoute
    }
    '/practical/ceremony': {
      id: '/practical/ceremony'
      path: '/ceremony'
      fullPath: '/practical/ceremony'
      preLoaderRoute: typeof PracticalCeremonyRouteImport
      parentRoute: typeof PracticalRoute
    }
    '/practical/booklet': {
      id: '/practical/booklet'
      path: '/booklet'
      fullPath: '/practical/booklet'
      preLoaderRoute: typeof PracticalBookletRouteImport
      parentRoute: typeof PracticalRoute
    }
    '/practical/atmosphere': {
      id: '/practical/atmosphere'
      path: '/atmosphere'
      fullPath: '/practical/atmosphere'
      preLoaderRoute: typeof PracticalAtmosphereRouteImport
      parentRoute: typeof PracticalRoute
    }
    '/garden/$zone': {
      id: '/garden/$zone'
      path: '/garden/$zone'
      fullPath: '/garden/$zone'
      preLoaderRoute: typeof GardenZoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compose/$zone': {
      id: '/compose/$zone'
      path: '/compose/$zone'
      fullPath: '/compose/$zone'
      preLoaderRoute: typeof ComposeZoneRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PracticalRouteChildren {
  PracticalAtmosphereRoute: typeof PracticalAtmosphereRoute
  PracticalBookletRoute: typeof PracticalBookletRoute
  PracticalCeremonyRoute: typeof PracticalCeremonyRoute
  PracticalFlowersRoute: typeof PracticalFlowersRoute
  PracticalObjectsRoute: typeof PracticalObjectsRoute
  PracticalShareRoute: typeof PracticalShareRoute
  PracticalStepsRoute: typeof PracticalStepsRoute
  PracticalTextsRoute: typeof PracticalTextsRoute
  PracticalIndexRoute: typeof PracticalIndexRoute
}

const PracticalRouteChildren: PracticalRouteChildren = {
  PracticalAtmosphereRoute: PracticalAtmosphereRoute,
  PracticalBookletRoute: PracticalBookletRoute,
  PracticalCeremonyRoute: PracticalCeremonyRoute,
  PracticalFlowersRoute: PracticalFlowersRoute,
  PracticalObjectsRoute: PracticalObjectsRoute,
  PracticalShareRoute: PracticalShareRoute,
  PracticalStepsRoute: PracticalStepsRoute,
  PracticalTextsRoute: PracticalTextsRoute,
  PracticalIndexRoute: PracticalIndexRoute,
}

const PracticalRouteWithChildren = PracticalRoute._addFileChildren(
  PracticalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrisisRoute: CrisisRoute,
  DatesRoute: DatesRoute,
  HelpRoute: HelpRoute,
  HomeRoute: HomeRoute,
  InspirationRoute: InspirationRoute,
  JournalRoute: JournalRoute,
  MemoriesRoute: MemoriesRoute,
  OnboardingRoute: OnboardingRoute,
  PracticalRoute: PracticalRouteWithChildren,
  PresenceRoute: PresenceRoute,
  SpaceRoute: SpaceRoute,
  WishesRoute: WishesRoute,
  ComposeZoneRoute: ComposeZoneRoute,
  GardenZoneRoute: GardenZoneRoute,
  GardenIndexRoute: GardenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
